source: [betterprogramming](https://betterprogramming.pub/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d)

In [1]:
import numpy as np

![alt text](https://miro.medium.com/max/720/1*XbZqTBXZmnQtVZ_llbGJTw.png)

NumPy arrays are:
more compact, especially when there’s more than one dimension
faster than lists when the operation can be vectorized
slower than lists when you append elements to the end
usually homogeneous: can only work fast with elements of one type

# Vectors, the 1D Arrays

## Vector initialization

In [2]:
# from python list
a = np.array([1., 2., 3.])
print(a.dtype)
print(a.shape)

float64
(3,)


NumPy arrays cannot grow the way a Python list does: No space is reserved at the end of the array to facilitate quick appends. So it is a common practice to either grow a Python list and convert it to a NumPy array when it is ready or to preallocate the necessary space with np.zeros or np.empty

In [3]:
b = np.zeros(4, int)
print(f'b -> {b}')
c = np.zeros_like(a)
print(f'c -> {c}')

b -> [0 0 0 0]
c -> [0. 0. 0.]


Actually, all the functions that create an array filled with a constant value have a _like counterpart:
example: ones_like(a), full_like(a, 7)

In [4]:
d = np.full_like(a, 6)
print(d)

[6. 6. 6.]


two functions for array initialization with a monotonic sequence in NumPy

In [5]:
e = np.arange(6)
print(e)
e = np.arange(3,6) #(start, stop)
print(e)
e = np.arange(1,10,2) #(start, stop, step)
print(e)


[0 1 2 3 4 5]
[3 4 5]
[1 3 5 7 9]


If you need a similar-looking array of floats, like [0., 1., 2.], you can change the type of the arange output: arange(3).astype(float), but there’s a better way. The arange function is type-sensitive: If you feed ints as arguments, it will generate ints, and if you feed floats (e.g., arange(3.)) it will generate floats.

But arange is not especially good at handling floats:

In [6]:
e = np.linspace(0.3, 1.5, 5) # (start, stop, num)
print(e)


[0.3 0.6 0.9 1.2 1.5]


Random Arrays

In [7]:
r = np.random.randint(0, 10, 4) #[0, 100)
print(r)
r = np.random.random(3) # uniform x ∈ [0, 1)
print(r)
r = np.random.randn(3) # normal µ = 0, sigma = 1
print(r)
r = np.random.uniform(1, 10, 3) # uniform x ∈ [0, 10)
print(r)
r = np.random.normal(5, 2, 3) # normal µ = 5, sigma = 2
print(r)

[7 5 9 8]
[0.68425628 0.24802488 0.418875  ]
[ 1.05302015 -0.08033821  0.94184442]
[1.00775847 3.47420787 9.94062994]
[2.64005418 3.59796761 7.47340688]


## Vector indexing

![alt text](https://miro.medium.com/max/720/1*4xpufyWZWcIbabsOHVlc4g.png)

In [8]:
i = np.arange(1, 6)
print(i)
print(i[1])
print(i[2:4]) # [2, 4)
print(i[-3:])
print(i[::2])
print(i[[1, 3, 4]])
print(i)
i[2:4] = 0 # such assignments must not change the size of the array,
print(i)
i[2:4] = [3, 4]
print(i)

[1 2 3 4 5]
2
[3 4]
[3 4 5]
[1 3 5]
[2 4 5]
[1 2 3 4 5]
[1 2 0 0 5]
[1 2 3 4 5]


![alt text](https://miro.medium.com/max/720/1*nFGcXav_xxD7TXGiRYMpHg.png)

In [9]:
print(np.any(i > 4))
print(np.any(i > 6))
print(i[i > 3]) #Python “ternary” comparisons like 3<=a<=5 don’t work here
print(i[(i > 3) & (i < 5)])

True
False
[4 5]
[4]


![alt text](https://miro.medium.com/max/720/1*Dv9HzG2dSf3QuhjfpSIhqA.png)

![alt text](https://miro.medium.com/max/720/1*fLUqfXDFbKtGVBl5VwuySQ.png)

## Vector operations


![alt text](https://miro.medium.com/max/720/1*RNfQubSwH_6-GnWHVjn9CQ.png)

The same way ints are promoted to floats when adding or subtracting, scalars are promoted (aka broadcasted) to arrays

Most of the math functions have NumPy counterparts that can handle vectors:

![alt text](https://miro.medium.com/max/1400/1*Pc4t0jilbHSM0sMwtVNGIA.png)

Scalar product has an operator of its own:
![alt text](https://miro.medium.com/max/1400/1*rDUgKZO4bj9_SSRY6ddnfg.png)

In [10]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(a@b)

20


You don’t need loops for trigonometry either:

![alt text](https://miro.medium.com/max/1400/1*wyHVvsoUdsHA0RedM6kdvQ.png)


Arrays can be rounded as a whole:

![alt text](https://miro.medium.com/max/1400/1*GkjXtrFriVBXTQove8vEPw.png)


NumPy is also capable of doing the basic stats:

![alt text](https://miro.medium.com/max/1400/1*TAB7WXfvTM7FxD1bJ7augQ.png)


![alt text](https://miro.medium.com/max/720/1*3TUC2TP7AG6MTGmNNCx_hg.png)

Pandas std uses Bessel’s correction by default

### Searching for an element in a vector

![alt text](https://miro.medium.com/max/720/1*bQXR_BLBC91f5WvH4TaFcw.png)


### Comparing floats

![alt text](https://miro.medium.com/max/720/1*LZWByfm3vyHXhNreHGy3hQ.png)


# Matrices, the 2D Arrays

![alt text](https://miro.medium.com/max/720/1*aLMuXA81pDXaw0J0QdKvRQ.png)


![alt text](https://miro.medium.com/max/720/1*O9bawffUMaZeQw1g0DuHrg.png)


![alt text](https://miro.medium.com/max/720/1*zOgsZhCTMnbJWC5u_I3fiQ.png)


Two-dimensional indexing syntax is more convenient than that of nested lists:

![alt text](https://miro.medium.com/max/720/1*brbsl7QFZGWfmvgFHMwt9Q.png)
